apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: stroke-mlops
spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: hazem231/stroke-backend:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 8082

          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: stroke-config
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: stroke-config
                  key: MYSQL_USER

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stroke-secret
                  key: MYSQL_PASSWORD

            - name: APP_FASTAPI_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: stroke-config
                  key: APP_FASTAPI_BASE_URL

          readinessProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 20