spring.application.name=stroke_backend

spring.datasource.url=jdbc:mysql://localhost:3306/stroke_mlops
spring.datasource.username=stroke_user
spring.datasource.password=stroke_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8082
server.servlet.context-path=/stroke_ml