sonar.projectKey=stroke-frontend
sonar.projectName=Stroke Frontend
sonar.sources=src/app
sonar.tests=src/app
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/dist/**,**/coverage/**,**/public/**
